Repository gpwn/CampFire_BE, pull requests merged in 2023-01, with the labels that each got.

#5 <FEAT> DB생성 :card_file_box:
  src/architecture/controllers/camps.controller.js
  src/architecture/controllers/test.js
  src/architecture/repositories/camps.repository.js
  src/architecture/repositories/test.js
  src/architecture/services/camps.service.js
  src/architecture/services/test.js
  src/config/config.js
  src/migrations/20221231053827-create-users.js
  src/migrations/20221231053828-create-hosts.js
  src/migrations/20221231054630-create-camps.js
  src/migrations/20221231054909-create-books.js
  src/models/books.js
  src/models/camps.js
  src/models/hosts.js
  src/models/index.js
  src/models/users.js
  src/routes/camps.route.js
  src/routes/index.js
Labels: enhancement

#9 <FEAT> 로그인API기능구현 완료 :sparkles:
  package-lock.json
  package.json
  src/app.js
  src/architecture/controllers/hosts.controller.js
  src/architecture/controllers/users.controller.js
  src/architecture/repositories/hosts.repository.js
  src/architecture/repositories/users.repository.js
  src/architecture/services/hosts.service.js
  src/architecture/services/users.service.js
  src/middlewares/authHost.middleware.js
  src/middlewares/authLoginHost.middleware.js
  src/middlewares/authLoginUser.middleware.js
  src/middlewares/authUser.middleware.js
  src/middlewares/error.handler.middleware.js
  src/migrations/20221231053828-create-hosts.js
  src/models/hosts.js
  src/models/index.js
  src/modules/profileImg.js
  src/routes/hosts.route.js
  src/routes/index.js
  src/routes/users.route.js
  src/util/auth-encryption.util.js
  src/util/auth-jwtToken.util.js
Labels: enhancement

#13 <FEAT> 캠핑장수정/삭제/예약 API 구현 완료 ✨Feature/campupdate
  src/architecture/controllers/camps.controller.js
  src/architecture/repositories/camps.repository.js
  src/architecture/services/camps.service.js
  src/middlewares/error.handler.middleware.js
  src/migrations/20221231054630-create-camps.js
  src/models/camps.js
  src/modules/campImg.js
  src/modules/test.js
  src/routes/camps.route.js
  src/routes/index.js
Labels: enhancement

#15 <FEAT> 캠핑장 업로드/페이지 조회/상세 조회 API 기능 구현 :sparkles:
  .gitignore
  src/architecture/controllers/camps.controller.js
  src/architecture/repositories/camps.repository.js
  src/architecture/services/camps.service.js
  src/routes/camps.route.js
Labels: enhancement

#97 <FIX> 캠핑장 페이지 조회 API 수정 :art:
  .dockerignore
  Dockerfile
  src/architecture/repositories/camps.repository.js
  src/architecture/services/camps.service.js
Labels: documentation

#99 <FIX> campupdate api bug fix/delete api update :bug:
  src/app.js
  src/architecture/controllers/camps.controller.js
  src/architecture/services/camps.service.js
  src/modules/campImg.js
  src/modules/modules.js
  src/routes/camps.route.js
Labels: documentation

#107 <FEAT> hostAPI 기능 최신화 및 사업자확인API 구 현
  package-lock.json
  package.json
  src/architecture/controllers/hosts.controller.js
  src/architecture/controllers/users.controller.js
  src/architecture/repositories/camps.repository.js
  src/architecture/repositories/hosts.repository.js
  src/architecture/repositories/users.repository.js
  src/architecture/services/hosts.service.js
  src/architecture/services/users.service.js
  src/migrations/20221231053828-create-hosts.js
  src/models/hosts.js
  src/routes/hosts.route.js
  src/routes/users.route.js
Labels: enhancement

#111 <FEAT> user,host 예약 조회 기능 구현 및 캠핑장,사이트 목록조회,상세조회 수정 :art::sparkles:
  src/architecture/controllers/books.controller.js
  src/architecture/controllers/camps.controller.js
  src/architecture/repositories/books.repository.js
  src/architecture/repositories/camps.repository.js
  src/architecture/services/books.service.js
  src/architecture/services/camps.service.js
  src/routes/books.route.js
  src/routes/camps.route.js
  src/routes/index.js
Labels: documentation, enhancement

#113 <FEAT> 캠핑장 API 수정 및 체크박스 키워드 등록,수정 및 사이트 등록/수정/삭제 API 기능 구현 완료:art::sparkles:
  src/architecture/controllers/camps.controller.js
  src/architecture/controllers/sites.controller.js
  src/architecture/repositories/camps.repository.js
  src/architecture/repositories/sites.repository.js
  src/architecture/services/camps.service.js
  src/architecture/services/sites.service.js
  src/config/config.js
  src/routes/camps.route.js
  src/routes/index.js
  src/routes/sites.route.js
Labels: enhancement

#122 <FIX> 캠핑장 상세조회/등록 API 수정 및 캠핑장 키워드 체크박스 등록 API 삭제 :art:
  src/architecture/controllers/camps.controller.js
  src/architecture/repositories/camps.repository.js
  src/architecture/services/camps.service.js
  src/routes/camps.route.js
Labels: documentation

#126 <FIX> 캠핑장 리스트 조회 시 typeLists추가 및 예약 조회시 sites 추가 #123 :art:
  src/architecture/repositories/books.repository.js
  src/architecture/repositories/camps.repository.js
  src/architecture/services/books.service.js
  src/architecture/services/camps.service.js
Labels: documentation

#130 <FEAT> 카카오 로그인 구현
  package-lock.json
  package.json
  src/architecture/controllers/auths.controller.js
  src/architecture/repositories/auths.repository.js
  src/architecture/services/auths.service.js
  src/migrations/20221231053827-create-users.js
  src/models/users.js
  src/routes/auths.routes.js
  src/routes/index.js
Labels: enhancement

#133 <FIX> 캠핑장 키워드 체크박스 API 메소드 수정 및 코드 수정 :art:
  src/architecture/controllers/camps.controller.js
  src/routes/camps.route.js
Labels: documentation

#135 <FIX> 캠핑장 키워드 체크박스 API 수정 :art:
  src/architecture/repositories/camps.repository.js
Labels: documentation

#136 <FIX> 캠핑장 키워드 체크박스 API 수정 :art:
  src/architecture/repositories/camps.repository.js
Labels: documentation

#142 <FEAT> like기능 구현 ✨ #116
  src/architecture/controllers/camps.controller.js
  src/architecture/controllers/likes.controller.js
  src/architecture/repositories/likes.repository.js
  src/architecture/services/camps.service.js
  src/architecture/services/likes.service.js
  src/middlewares/likeConfirmUser.middleware.js
  src/migrations/20221231053827-create-users.js
  src/migrations/20221231054630-create-camps.js
  src/migrations/20221231054910-create-likes.js
  src/models/camps.js
  src/models/likes.js
  src/models/users.js
  src/routes/camps.route.js
  src/routes/index.js
  src/routes/likes.route.js
Labels: enhancement

#144 <FEAT> 리뷰 작성, 조회, 수정, 삭제 API 기능 구현 완료 :sparkles:
  src/architecture/controllers/reviews.controller.js
  src/architecture/repositories/reviews.repository.js
  src/architecture/services/reviews.service.js
  src/migrations/20230111064415-create-reviews.js
  src/models/reviews.js
  src/routes/index.js
  src/routes/reviews.route.js
Labels: enhancement

#153 <FIX> 캠핑장 페이지 조회 API 수정 :memo:
  src/architecture/repositories/camps.repository.js
  src/architecture/services/camps.service.js
Labels: documentation

#156 <FIX> 캠핑장 페이지 조회 API 수정 :memo:
  src/architecture/controllers/camps.controller.js
  src/architecture/repositories/camps.repository.js
  src/architecture/services/camps.service.js
  src/routes/camps.route.js
Labels: documentation

#158 <FIX> 캠핑장 상세 조회 API 수정
  src/architecture/repositories/camps.repository.js
  src/architecture/services/camps.service.js
Labels: documentation

#167 <FIX> 특정 호스트 정보 조회 API 수정 :memo:
  src/architecture/repositories/hosts.repository.js
  src/architecture/services/hosts.service.js
Labels: documentation

#168 <FIX> 유저 예약조회,이용완료조회,취소조회 기능 구현 수정 :art: #143
  src/architecture/repositories/books.repository.js
  src/architecture/services/books.service.js
Labels: documentation
